# Generated by Django 5.0.4 on 2024-05-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisProject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_num', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('superviser', models.CharField(max_length=100)),
                ('relv_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
