# Generated by Django 5.0.4 on 2024-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as2_app', '0002_supervisor_remove_thesisproject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisproject',
            name='superviser',
            field=models.CharField(max_length=250),
        ),
    ]
